.gitignore, collector/collector.py, collector/collector_test.py, collector/context.py, collector/docker.py, collector/global_state.py, collector/kubernetes.py, collector/utilities.py
This is an intermediary step before the introduction of concurrent worker threads.
=> Change access to global information to use the GlobalState object.

collector/context.py, collector/kubernetes.py, collector/utilities.py
=> Fixes the generation of "loadBalances" and "monitors" relations.

collector/collector.py, collector/collector_test.py, collector/docker.py, collector/global_state.py, collector/simple_cache_test.py, collector/static/home.html, collector/utilities.py
=> Implement /health API endpoint and cache /version result.

collector/metrics.py, collector/testdata/containers.output.json, collector/testdata/nodes.output.json
Addresses a comment in issue #34.
=> simplify GCM metrics annotations.

collector/collector_test.py, collector/context.py, collector/utilities.py
=> Ensure that all resource objects contain a 'properties' attribute.

collector/collector.py, collector/collector_test.py, collector/static/home.html
Delete a superflous test in collector_test.py
Closes issue #50.
=> Rename the /health endpoint to /healthz.

collector/context.py, collector/docker.py, collector/kubernetes.py, collector/metrics.py, collector/utilities.py
Many modifications to match the new JSON responses format from Kubernetes. See issue #63.
This pull request does not contain new unit tests to match the new JSON data format. The new tests will be included in a following pull request.
=> Support Kubernetes API v1beta3.

README.md, collector/cluster_insight.py, collector/docker.py, collector/utilities.py
Fixed the API call to get the images
* Use /images/{image_id}/json instead of /containers/{image_id}/json
* Edit get_images() in docker.py to get the correct image_id
* Get the image_name from the container, and pass it to get_image() to assign a useful alternateLabel to the image
=> bug fix to get the data for images

collector/context.py, collector/docker.py, collector/kubernetes.py, collector/utilities.py
Fix assertion failure in get_image().
=> Fix assertion failure in get_image().

TROUBLESHOOTING.md
=> add a troubleshooting document

install/master-setup.sh
Couple of bug fixes to make the script run correctly when it's run locally and when there's not already a cluster-insight replication controller running on the master.
=> Fix two bugs in master-setup.sh

collector/cluster_insight.py, collector/collector_test.py, collector/context.py, collector/docker_proxy.py, collector/global_state.py, collector/utilities.py, collector/utilities_test.py
=> add a timestamp to every relation and fix many lint errors

collector/docker_proxy.py
=> Reduce the collector's response time.

collector/cluster-insight-controller.json
Modified the replication controller, so that the securityContext is set correctly for CentOS/Redhat instances.
=> Edited the replication controller to work with CentOS

README.md, collector/collector_test.py, collector/constants.py, collector/context.py, collector/simple_cache.py, collector/simple_cache_test.py, collector/utilities.py, collector/utilities_test.py
This is the remaining code and unit tests for implementing #81.
=> compute 'timestamp' values correctly

install/cluster-insight-setup.sh
1) verify that the requested API version is supported by the underlying Kubernetes.
2) verify that the Cluster-Insight output contains all expected resources.
3) document functions.
4) cleanup parameter matching code.
=> improvements to the installation script

README.md
Explain new features of the Cluster-Insight installations and execution:
1) supported API versions.
2) install and run in debug mode.
3) tags of released images.
=> enhance README.md file

collector/cluster_insight.py, collector/collector.py
Also removed some unused code.
=> Add --host as a command line option.

collector/collector_error.py, collector/context.py, collector/kubernetes.py, collector/metrics.py
See commit messages for details.
=> Stylistic improvements

collector/collector.py, collector/collector_test.py, collector/constants.py, collector/context.py, collector/global_state.py, collector/kubernetes.py, collector/utilities.py
IMHO, wrapping of the Python logger interface is somewhat of an anti-pattern.
See the commit messages for details.
=> Use Flask logging in a more idiomatic way.
